//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbarrotesGenerales.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbarrotesGenerales.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///    &lt;h2&gt;Instituto Tecnológico de México, Campus Mexicali&lt;/h2&gt;
        ///    &lt;h2&gt;Abarrotes Generales&lt;/h2&gt;
        ///    &lt;h2&gt;Reporte de Adeudos por Estado&lt;/h2&gt;
        ///    &lt;div align=&quot;right&quot;&gt;@fecha&lt;/div&gt;
        ///    &lt;p align=&quot;right&quot;&gt;@pag&lt;/p&gt;
        ///    &lt;div&gt;Estado: @estado&lt;/div&gt;
        ///    &lt;p&gt;&lt;/p&gt;
        ///
        ///    &lt;table class=&quot;border&quot; border=&quot;1&quot; style=&quot;width:100%&quot;&gt;
        ///        &lt;tr style=&quot;background-color: #D8D8D8&quot;&gt;
        ///            &lt;td style=&quot;width:10%&quot;&gt;idAdeudo&lt;/td&gt;
        ///            &lt;td style=&quot;width:20%&quot;&gt;fechaAdeudo&lt;/td&gt;
        ///            &lt;td  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string reporteadeudos {
            get {
                return ResourceManager.GetString("reporteadeudos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///    &lt;h2&gt;Instituto Tecnológico de México, Campus Mexicali&lt;/h2&gt;
        ///    &lt;h2&gt;Abarrotes Generales&lt;/h2&gt;
        ///    &lt;h2&gt;Reporte de Entradas por Periodo&lt;/h2&gt;
        ///    &lt;div align=&quot;right&quot;&gt;@fechareporte&lt;/div&gt;
        ///    &lt;p align=&quot;right&quot;&gt;@pag&lt;/p&gt;
        ///    &lt;div&gt;Periodo: @fechauno - @fechados&lt;/div&gt;
        ///    &lt;p&gt; &lt;/p&gt;
        ///
        ///    &lt;table class=&quot;border&quot; border=&quot;1&quot; style=&quot;width:100%&quot;&gt;
        ///        &lt;tr style=&quot;background-color: #D8D8D8&quot;&gt;
        ///            &lt;td style=&quot;width:25%&quot;&gt;idEntrada&lt;/td&gt;
        ///            &lt;td style=&quot;width:25%&quot;&gt;fechaEnt [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string reporteentradas {
            get {
                return ResourceManager.GetString("reporteentradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///    &lt;h2&gt;Instituto Tecnológico de México, Campus Mexicali&lt;/h2&gt;
        ///    &lt;h2&gt;Abarrotes Generales&lt;/h2&gt;
        ///    &lt;h2&gt;Reporte de Inventario por Categoría&lt;/h2&gt;
        ///    &lt;div align=&quot;right&quot;&gt;@fecha&lt;/div&gt;
        ///    &lt;p align=&quot;right&quot;&gt;@pag&lt;/p&gt;
        ///    &lt;div&gt;Clave de Categoria: @idcat | Nombre de Categoria: @nomcat&lt;/div&gt;
        ///    &lt;p&gt;&lt;/p&gt;
        ///
        ///    &lt;table class=&quot;border&quot; border=&quot;1&quot; style=&quot;width:100%&quot;&gt;
        ///        &lt;tr style=&quot;background-color: #D8D8D8&quot;&gt;
        ///            &lt;td style=&quot;width:5%&quot;&gt;idArticulo&lt;/td&gt;
        ///            &lt;td&gt;nom [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string reporteinventario {
            get {
                return ResourceManager.GetString("reporteinventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///    &lt;h2&gt;Instituto Tecnológico de México, Campus Mexicali&lt;/h2&gt;
        ///    &lt;h2&gt;Abarrotes Generales&lt;/h2&gt;
        ///    &lt;h2&gt;Reporte de Entradas por Periodo&lt;/h2&gt;
        ///    &lt;div align=&quot;right&quot;&gt;@fechareporte&lt;/div&gt;
        ///    &lt;p align=&quot;right&quot;&gt;@pag&lt;/p&gt;
        ///    &lt;div&gt;Periodo: @fechauno - @fechados&lt;/div&gt;
        ///    &lt;p&gt; &lt;/p&gt;
        ///
        ///    &lt;table class=&quot;border&quot; border=&quot;1&quot; style=&quot;width:100%&quot;&gt;
        ///        &lt;tr style=&quot;background-color: #D8D8D8&quot;&gt;
        ///            &lt;td style=&quot;width:25%&quot;&gt;idEntrada&lt;/td&gt;
        ///            &lt;td style=&quot;width:25%&quot;&gt;fechaEnt [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string reporteventas {
            get {
                return ResourceManager.GetString("reporteventas", resourceCulture);
            }
        }
    }
}
